#!/usr/bin/env bash
#
# Start the application

if ! command -v docker-compose &>/dev/null; then
  echo "Error! Missing dependency: docker-compose. Please install and try again."
  exit 1
elif ! docker info &>/dev/null; then
  echo "The Docker daemon doesn't appear to be running. Please start Docker and try again."
  exit 1
fi

docker-compose up --build
